version: "3.8"

# NOTE (JGMW): See the package.json on Brendan's PR for the scripts that can be helpful

# Testing inside console:
# curl -G -v "http://api:8911/graphql" --data-urlencode "query={redwood{version}}" -w "\n"
# curl -G -v "http://web:8910/" --data-urlencode "query={redwood{version}}" -w "\n"

services:
  # Console notes:
  #  - Might not want to include by default
  #  - Can be useful to run commands without having all the dependencies installed locally
  #  - Can run using `docker compose run --rm console /bin/bash`
  #
  # This builds the base container. Useful for a 'console' to debug things with
  console:
    # we have to be root to share folders into the container, but if you're debugging
    # an issue you should _not_ share the code and change this to docker to mimic production
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
      target: console
    tmpfs:
      - /tmp
    command: "true"
    environment:
      - DATABASE_URL=postgresql://redwood:redwood@db:5432/redwood
      - TEST_DATABASE_URL=postgresql://redwood:redwood@db:5432/redwood_test

  # Redwood API
  api:
    image: redwoodjs-project/api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: serve_api
    ports:
      - "8911:8911"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://redwood:redwood@db:5432/redwood
      - TEST_DATABASE_URL=postgresql://redwood:redwood@db:5432/redwood_test
      - SESSION_SECRET=super_secret_session_key_change_me_in_production_please

  # Redwood Web
  web:
    image: redwoodjs-project/web-serve:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: serve_web
    ports:
      - "8910:8910"
    depends_on:
      - api
    environment:
      - API_HOST=http://api:8911

  # Postgres DB
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: redwood
      POSTGRES_PASSWORD: redwood
      POSTGRES_DB: redwood
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
