# See the full yml reference at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: serverless-aws-web

# Uncomment `org` and `app` and enter manually if you want to integrate your
# deployment with the Serverless dashboard, or run `yarn serverless` in ./web to be
# prompted to connect to an app and these will be filled in for you.
# See https://www.serverless.com/framework/docs/dashboard/ for more details.
# org: redwoodjs
# app: serverless-aws-web

useDotenv: true

plugins:
  - serverless-lift

constructs:
  web:
    type: static-website
    path: dist
    extensions: {
      bucket: {
        Properties: {
          PublicAccessBlockConfiguration: {
            BlockPublicPolicy: false,
          }
        }
      }
    }

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2 # AWS region where the service will be deployed, defaults to N. Virgina
