name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]     

jobs:
  netlifyCI:
    name: Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Run Netlify CI
        uses: redwoodjs/project-ci-action@main
        with:
          project-directory: './netlify'
          run-lint: 'no'

  vercelCI:
    name: Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Run Vercel CI
        uses: redwoodjs/project-ci-action@main
        with:
          project-directory: './vercel'
          run-lint: 'no'

  renderPostgresCI:
    name: Render-Postgres
    runs-on: ubuntu-latest
    steps:
      - name: Run Render-Postgres CI
        uses: redwoodjs/project-ci-action@main
        with:
          project-directory: './render-postgres'
          run-lint: 'no'

  serverlessAwsCI:
    name: Serverless-AWS
    runs-on: ubuntu-latest
    steps:
      - name: Run Serverless-AWS CI
        uses: redwoodjs/project-ci-action@main
        with:
          project-directory: './serverless-aws'
          run-lint: 'no' 

  baremetal:
    name: baremetal
    runs-on: ubuntu-latest
    steps:
      - name: Run Baremetal CI
        uses: redwoodjs/project-ci-action@main
        with:
          project-directory: './baremetal'
          run-lint: 'no' 

  flightcontrol:
    name: Flightcontrol
    runs-on: ubuntu-latest
    steps:
      - name: Run Flightcontrol CI
        uses: redwoodjs/project-ci-action@main
        with:
          project-directory: './flightcontrol'
          run-lint: 'no' 

  layer0:
    name: layer0
    runs-on: ubuntu-latest
    steps:
      - name: Run Layer0 CI
        uses: redwoodjs/project-ci-action@main
        with:
          project-directory: './layer0'
          run-lint: 'no'                               
