name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]     

# Eventually this needs to use .github/actions/project-ci
# Currently can't get it to work without the "needs version" error
jobs:
  Netlify:
    name: Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'
          postgresql user: test
          postgresql password: password

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-    

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./netlify"
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      - name: Run Diagnostics
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test

  vercelCI:
    name: Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'
          postgresql user: test
          postgresql password: password

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-    

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./vercel"
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      - name: Run Diagnostics
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test

  renderCI:
    name: Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'
          postgresql user: test
          postgresql password: password

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-    

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./render-postgres"
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      - name: Run Diagnostics
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test

  serverlessCI:
    name: Serverless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'
          postgresql user: test
          postgresql password: password

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-    

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./serverless-aws"
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      - name: Run Diagnostics
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test    

  baremetal:
    name: baremetal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'
          postgresql user: test
          postgresql password: password

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-    

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./baremetal"
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      - name: Run Diagnostics
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test

  flightcontrol:
    name: Flightcontrol
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'
          postgresql user: test
          postgresql password: password

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-    

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./flightcontrol"
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      - name: Run Diagnostics
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test 

  layer0:
    name: layer0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'
          postgresql user: test
          postgresql password: password

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-    

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./layer0"
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      - name: Run Diagnostics
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://test:password@localhost:5432/test                              
