name: Deploy Serverless AWS

on:
  push:
    branches: [ main ]

# maybe I don't need this...
  # workflow_run:
  #   workflows: [Merge Renovate]
  #   types:
  #     - completed    

jobs:
  build:
    if: github.repository == 'redwoodjs/deploy-target-ci'
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.SERVERLESS_DATABASE_URL }}
      API_URL: ${{ secrets.SERVERLESS_API_URL}}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: |
          yarn install --immutable
        working-directory: ./serverless-aws

      - name: Build Serverless
        run: |
          yarn rw deploy serverless --pack-only
        working-directory: ./serverless-aws

      - name: Deploy
        run: |
          yarn rw deploy serverless
        working-directory: ./serverless-aws
          